services:
  common_backend:
    build:
      args:
        DOCKER_HOST_UID: ${DOCKER_HOST_UID:?}
        DOCKER_HOST_GID: ${DOCKER_HOST_GID:?}
      context: .
    environment:
        TZ: "Europe/Moscow"
        XDG_CONFIG_HOME: "/var/www/.xdg"
        PHP_INI_SCAN_DIR: ":/usr/local/etc/php/custom.d"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    user: ${DOCKER_HOST_UID:?}
    volumes:
      - ./:/var/www
      - ./.docker/php/conf.d/app.ini:/usr/local/etc/php/conf.d/app.ini
      - ./.docker/php/custom.d/:/usr/local/etc/php/custom.d/
    working_dir: /var/www/
